import { Category } from '../types';

/**
 * PENDING TOOLS - Holding Pen for Unapproved Discoveries
 * 
 * Auto-generated by Tool Scout on 2026-02-01T09:35:31.617Z
 * Total tools pending: 25
 */

export const PENDING_TOOLS: Partial<Category>[] = [
  {
    id: '1',
    title: 'Research, Discovery & Strategy',
    tools: [
      {
        name: 'Emra / Always on Transcription and PTT',
        url: 'https://www.producthunt.com/products/emra',
        description: 'Ensure zero data loss from user interviews and design discussions by continuously transcribing speech, allowing you to focus completely on the convers',
        dateAdded: '2026-01-31T01:44:20.605Z'
      },
      {
        name: 'Dottie',
        url: 'https://www.producthunt.com/products/dottie',
        description: 'Dottie synthesizes unstructured user interviews and competitive analysis into prioritized feature recommendations ready for sketching.',
        dateAdded: '2026-01-31T09:33:03.489Z'
      },
      {
        name: 'Hyta',
        url: 'https://www.producthunt.com/products/hyta',
        description: 'The tool synthesizes unstructured user feedback data into prioritized insights, directly informing your next design sprint objectives.',
        dateAdded: '2026-02-01T09:35:08.760Z'
        // Source: Product Hunt
      }
    ]
  },
  {
    id: '2',
    title: 'Ideation & Concept Design',
    tools: [
      {
        name: 'Good Assistant',
        url: 'https://www.producthunt.com/products/good-assistant',
        description: 'Good Assistant rapidly converts sketched concepts or rough user flows into structured wireframes, allowing for quicker internal iteration cycles.',
        dateAdded: '2026-02-01T09:35:00.976Z'
        // Source: Product Hunt
      }
    ]
  },
  {
    id: '3',
    title: 'UI Design & Prototyping',
    tools: [
      {
        name: 'Kokori',
        url: 'https://www.producthunt.com/products/kokori',
        description: 'Kokori automatically generates and refines complete user interface layouts based on functional requirements, allowing designers to move directly into ',
        dateAdded: '2026-01-31T01:44:28.056Z'
      },
      {
        name: 'Leapility',
        url: 'https://www.producthunt.com/products/leapility-3',
        description: 'Leapility instantly converts your scribbled design concepts into functional, interactive prototypes ready for user testing.',
        dateAdded: '2026-01-31T01:44:51.087Z'
      },
      {
        name: 'Archimyst',
        url: 'https://www.producthunt.com/products/archimyst',
        description: 'Archimyst quickly generates multiple, high-fidelity screen variations from a basic sketch, allowing you to test complex user flows more rapidly.',
        dateAdded: '2026-01-31T01:44:58.803Z'
      },
      {
        name: 'RUSTWA',
        url: 'https://www.producthunt.com/products/rustwa',
        description: 'RUSTWA automatically verifies your design drafts against accessibility standards and simulates their appearance on diverse device configurations befor',
        dateAdded: '2026-01-31T09:32:55.680Z'
      }
    ]
  },
  {
    id: '4',
    title: 'Content, Microcopy & UX Writing',
    tools: [
      {
        name: 'Lost Post',
        url: 'https://www.producthunt.com/products/lost-post-worldwide-question-of-the-day',
        description: 'Lost Post instantly generates precise microcopy, error messages, and instructional labels, ensuring your prototypes always communicate clearly.',
        dateAdded: '2026-01-31T01:44:43.837Z'
      },
      {
        name: 'Pretty Prompt 1.0 Extension + Web App',
        url: 'https://www.producthunt.com/products/pretty-prompt',
        description: 'You can instantly optimize your generative AI prompts to reliably create production-ready microcopy, labels, and user guidance text for your product i',
        dateAdded: '2026-01-31T09:32:25.076Z'
      },
      {
        name: 'Herodot AI',
        url: 'https://www.producthunt.com/products/herodot-ai',
        description: 'Herodot AI automatically drafts precise button labels, error messages, and onboarding text based on the specific wireframe context you input.',
        dateAdded: '2026-01-31T09:32:40.496Z'
      },
      {
        name: 'Yomio',
        url: 'https://www.producthunt.com/products/yomio',
        description: 'Yomio analyzes user interview transcripts to quickly generate five distinct content options for complex empty states and error messages.',
        dateAdded: '2026-02-01T09:35:16.665Z'
        // Source: Product Hunt
      },
      {
        name: 'Reavion',
        url: 'https://www.producthunt.com/products/reavion',
        description: 'Reavion automatically drafts concise, context-aware microcopy and placeholder text directly inside your working prototype files.',
        dateAdded: '2026-02-01T09:35:24.464Z'
        // Source: Product Hunt
      }
    ]
  },
  {
    id: '7',
    title: 'Workflow Automation & Operations',
    tools: [
      {
        name: 'Geekflare API',
        url: 'https://www.producthunt.com/products/geekflare-api',
        description: 'This tool automatically extracts and compiles all necessary design specifications, measurements, and tokens directly from your mockups, eliminating ma',
        dateAdded: '2026-01-31T01:44:36.459Z'
      },
      {
        name: 'DestMate: Travel Alarm',
        url: 'https://www.producthunt.com/products/destmate-travel-alarm',
        description: 'This tool manages project deadlines and meeting times across multiple time zones, delivering clear, context-specific alerts directly into your design ',
        dateAdded: '2026-01-31T09:32:33.040Z'
      },
      {
        name: 'skills.sh',
        url: 'https://www.producthunt.com/products/vercel',
        description: 'skills.sh handles repetitive preparation steps—like naming layers, organizing files, and drafting documentation—so you spend more time validating prod',
        dateAdded: '2026-01-31T09:32:48.693Z'
      },
      {
        name: 'Compressor',
        url: 'https://www.producthunt.com/products/compressor-2',
        description: 'Compressor handles all batch exports and asset preparation instantly, freeing up your design time from repetitive file management.',
        dateAdded: '2026-02-01T09:34:52.615Z'
        // Source: Product Hunt
      },
      {
        name: 'Time Ledger',
        url: 'https://www.producthunt.com/products/time-ledger',
        description: 'Automatically log and categorize the precise time spent on deep design work versus administrative tasks, providing accurate effort metrics for project',
        dateAdded: '2026-02-01T09:35:31.617Z'
        // Source: Product Hunt
      }
    ]
  },
  {
    id: '12',
    title: 'Multimodal AI (Beyond Text)',
    tools: [
      {
        name: 'Grok Imagine API',
        url: 'https://www.producthunt.com/products/grok-3',
        description: 'A new AI tool for designers',
        dateAdded: '2026-01-31T01:45:03.003Z'
      },
      {
        name: 'Webhound Reports',
        url: 'https://www.producthunt.com/products/webhound',
        description: 'A new AI tool for designers',
        dateAdded: '2026-01-31T01:45:07.208Z'
      },
      {
        name: 'Sheetsbase',
        url: 'https://www.producthunt.com/products/sheetsbase-stop-googling-formulas',
        description: 'A new AI tool for designers',
        dateAdded: '2026-01-31T01:45:11.397Z'
      },
      {
        name: 'NMTV',
        url: 'https://www.producthunt.com/products/nmtv',
        description: 'A new AI tool for designers',
        dateAdded: '2026-01-31T01:45:15.573Z'
      },
      {
        name: 'ClaudeUsageBar',
        url: 'https://www.producthunt.com/products/claudeusagebar',
        description: 'A new AI tool for designers',
        dateAdded: '2026-01-31T09:33:07.591Z'
      },
      {
        name: 'Cntrl Bridge',
        url: 'https://www.producthunt.com/products/cntrl-bridge',
        description: 'A new AI tool for designers',
        dateAdded: '2026-01-31T09:33:11.690Z'
      },
      {
        name: 'TENDERD',
        url: 'https://www.producthunt.com/products/tenderd',
        description: 'A new AI tool for designers',
        dateAdded: '2026-01-31T09:33:15.793Z'
      }
    ]
  }
];
